# Generated by Django 3.2.7 on 2021-10-02 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='author')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('category', models.CharField(max_length=30, verbose_name='author')),
                ('abstract', models.CharField(max_length=300, verbose_name='abstract')),
                ('text', models.TextField(verbose_name='text')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 22, 28, 4, 361897), verbose_name='publish date')),
            ],
        ),
    ]
