# Generated by Django 3.2.7 on 2021-10-07 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published?'),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='category',
            field=models.CharField(max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 3, 5, 36, 334296), verbose_name='publish date'),
        ),
    ]
